name: Publish Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deps-cache-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Deno
      uses: actions/checkout@v2
      with:
        repository: denoland/deno
        path: deno
        ref: v1.6.3
        fetch-depth: 5
        submodules: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Cache layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx-
    - name: Build & push image
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./deno
        file: ./buster-slim.Dockerfile
        platforms: linux/arm64
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        tags: |
          ghcr.io/${{ github.repository_owner }}/deno-arm64:buster-slim
  # I already know this works, so let's just keep it commented out for now:
  # publish:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       base: ['debian', 'ubuntu']
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v1
  #   - name: Set up Docker Buildx
  #     id: buildx
  #     uses: docker/setup-buildx-action@v1
  #   - name: Log into registry
  #     uses: docker/login-action@v1
  #     with:
  #       registry: ghcr.io
  #       username: ${{ github.repository_owner }}
  #       password: ${{ secrets.CR_PAT }}
  #   - name: Cache layers
  #     uses: actions/cache@v2
  #     with:
  #       path: /tmp/.buildx-cache
  #       key: ${{ runner.os }}-buildx-${{ github.sha }}
  #       restore-keys: ${{ runner.os }}-buildx-
  #   - name: Build & push image
  #     uses: docker/build-push-action@v2
  #     with:
  #       push: true
  #       file: ./${{ matrix.base }}.Dockerfile
  #       platforms: linux/arm64
  #       builder: ${{ steps.buildx.outputs.name }}
  #       cache-from: type=local,src=/tmp/.buildx-cache
  #       cache-to: type=local,dest=/tmp/.buildx-cache
  #       tags: |
  #         ghcr.io/${{ github.repository_owner }}/deno-arm64:${{ matrix.base }}
